version: '3.8'
services:
  dynamodb-local:
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    image: 'amazon/dynamodb-local:latest'
    container_name: dynamodb-local
    ports:
      - '8000:8000'
    networks:
      - dynamodb-network
    volumes:
      - './dynamo-db:/home/dynamodblocal/data'
    working_dir: /home/dynamodblocal
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    ports:
      - '8001:8001'
    env_file:
      - .env
    environment:
      DYNAMO_ENDPOINT: 'http://dynamodb-local:8000'
      AWS_REGION: 'us-west-1'
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    networks:
      - dynamodb-network
    depends_on:
      - dynamodb-local

networks:
  dynamodb-network:
