# ./serverless.yml
service: serverless-adoring-virus-lambda

plugins:
  # - serverless-esbuild # used for compiling/packaging the Typescript code
  - serverless-plugin-typescript
  - serverless-tscpaths
  - serverless-dynamodb
  - serverless-offline # used for local execution
           
provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  httpApi:
    name: serverless-adoring-virus-lambda-http
    cors: true


functions:
  get_all_products:
    handler: ./src/functions/get-all/get-all.handler
    events:
      - httpApi:
          path: /api/products
          method: GET

  get_product_by_id:
    handler: ./src/functions/get-by-id/get-by-id.handler
    events:
      - httpApi:
          path: /api/products/{id+}
          method: GET

  create_product:
    handler: ./src/functions/create/create.handler
    events:
      - httpApi:
          path: /api/products
          method: POST


resources:
  - ${file(resources/stock-table.yml)}
  - ${file(resources/product-table.yml)}
