Resources:
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: product_table
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S

        # - AttributeName: title
        #   AttributeType: S

        # - AttributeName: description
        #   AttributeType: S

        # - AttributeName: price
        #   AttributeType: N

        # - AttributeName: count
        #   AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
