Resources:
  StockTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: stock_table
      AttributeDefinitions:
        - AttributeName: product_id
          AttributeType: S
        # - AttributeName: 'count'
        #   AttributeType: N
      KeySchema:
        - AttributeName: product_id
          KeyType: HASH
        # - AttributeName: 'count'
        #   KeyType: 'RANGE'
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST